package com.hntxrj.vo;

import lombok.Data;

import javax.persistence.Column;
import java.math.BigDecimal;
/*原材料统计汇总*/
@Data
public class RawCollectVO {
    /*线号*/
    private Integer stirId;
    /*方量*/
    private String qty;
    /* 配比材料名称砂一 */
    @Column(name = "mat1")
    private String mat1;
    /* 配比材料名称砂二 */
    @Column(name = "mat2")
    private String mat2;
    /* 配比材料名称砂三 */
    @Column(name = "mat3")
    private String mat3;
    /* 配比材料名称砂四 */
    @Column(name = "mat4")
    private String mat4;
    /* 配比材料名称石一 */
    @Column(name = "mat5")
    private String mat5;
    /* 配比材料名称石二 */
    @Column(name = "mat6")
    private String mat6;
    /* 配比材料名称石三 */
    @Column(name = "mat7")
    private String mat7;
    /* 配比材料名称石四 */
    @Column(name = "mat8")
    private String mat8;
    /* 配比材料名称水泥一 */
    @Column(name = "mat9")
    private String mat9;
    /* 配比材料名称水泥二 */
    @Column(name = "mat10")
    private String mat10;
    /* 配比材料名称水泥三 */
    @Column(name = "mat11")
    private String mat11;
    /* 配比材料名称水泥四 */
    @Column(name = "mat12")
    private String mat12;
    /* 配比材料名称矿粉 */
    @Column(name = "mat13")
    private String mat13;
    /* 配比材料名称粉煤灰 */
    @Column(name = "mat14")
    private String mat14;
    /* 配比材料名称粉外剂 */
    @Column(name = "mat15")
    private String mat15;
    /* 配比材料名称膨胀剂 */
    @Column(name = "mat16")
    private String mat16;
    /* 配比材料名称外加剂一 */
    @Column(name = "mat17")
    private String mat17;
    /* 配比材料名称外加剂二 */
    @Column(name = "mat18")
    private String mat18;
    /* 配比材料名称外加剂三 */
    @Column(name = "mat19")
    private String mat19;
    /* 配比材料名称外加剂四 */
    @Column(name = "mat20")
    private String mat20;
    /* 配比材料名称清水一 */
    @Column(name = "mat21")
    private String mat21;
    /* 配比材料名称清水二 */
    @Column(name = "mat22")
    private String mat22;
    /* 配比材料名称回收水 */
    @Column(name = "mat23")
    private String mat23;
    /* 预设值砂一 */
    @Column(name = "matv1")
    private String matV1;
    /* 预设值砂二 */
    @Column(name = "matv2")
    private String matV2;
    /* 预设值砂三 */
    @Column(name = "matv3")
    private String matV3;
    /* 预设值砂四 */
    @Column(name = "matv4")
    private String matV4;
    /* 预设值石一 */
    @Column(name = "matv5")
    private String matV5;
    /* 预设值石二 */
    @Column(name = "matv6")
    private String matV6;
    /* 预设值石三 */
    @Column(name = "matv7")
    private String matV7;
    /* 预设值石四 */
    @Column(name = "matv8")
    private String matV8;
    /* 预设值水泥一 */
    @Column(name = "matv9")
    private String matV9;
    /* 预设值水泥二 */
    @Column(name = "matv10")
    private String matV10;
    /* 预设值水泥三 */
    @Column(name = "matv11")
    private String matV11;
    /* 预设值水泥四 */
    @Column(name = "matv12")
    private String matV12;
    /* 预设值矿粉 */
    @Column(name = "matv13")
    private String matV13;
    /* 预设值粉煤灰 */
    @Column(name = "matv14")
    private String matV14;
    /* 预设值粉外剂 */
    @Column(name = "matv15")
    private String matV15;
    /* 预设值膨胀剂 */
    @Column(name = "matv16")
    private String matV16;
    /* 预设值外加剂一 */
    @Column(name = "matv17")
    private String matV17;
    /* 预设值外加剂二 */
    @Column(name = "matv18")
    private String matV18;
    /* 预设值外加剂三 */
    @Column(name = "matv19")
    private String matV19;
    /* 预设值外加剂四 */
    @Column(name = "matv20")
    private String matV20;
    /* 预设值清水一 */
    @Column(name = "matv21")
    private String matV21;
    /* 预设值清水二 */
    @Column(name = "matv22")
    private String matV22;
    /* 预设值回收水 */
    @Column(name = "matv23")
    private String matV23;
    /* 称量值砂一 */
    @Column(name = "matl1")
    private String matL1;
    /* 称量值砂二 */
    @Column(name = "matl2")
    private String matL2;
    /* 称量值砂三 */
    @Column(name = "matl3")
    private String matL3;
    /* 称量值砂四 */
    @Column(name = "matl4")
    private String matL4;
    /* 称量值石一 */
    @Column(name = "matl5")
    private String matL5;
    /* 称量值石二 */
    @Column(name = "matl6")
    private String matL6;
    /* 称量值石三 */
    @Column(name = "matl7")
    private String matL7;
    /* 称量值石四 */
    @Column(name = "matl8")
    private String matL8;
    /* 称量值水泥一 */
    @Column(name = "matl9")
    private String matL9;
    /* 称量值水泥二 */
    @Column(name = "matl10")
    private String matL10;
    /* 称量值水泥三 */
    @Column(name = "matl11")
    private String matL11;
    /* 称量值水泥四 */
    @Column(name = "matl12")
    private String matL12;
    /* 称量值矿粉 */
    @Column(name = "matl13")
    private String matL13;
    /* 称量值粉煤灰 */
    @Column(name = "matl14")
    private String matL14;
    /* 称量值粉外剂 */
    @Column(name = "matl15")
    private String matL15;
    /* 称量值膨胀剂 */
    @Column(name = "matl16")
    private String matL16;
    /* 称量值外加剂一 */
    @Column(name = "matl17")
    private String matL17;
    /* 称量值外加剂二 */
    @Column(name = "matl18")
    private String matL18;
    /* 称量值外加剂三 */
    @Column(name = "matl19")
    private String matL19;
    /* 称量值外加剂四 */
    @Column(name = "matl20")
    private String matL20;
    /* 称量值清水一 */
    @Column(name = "matl21")
    private String matL21;
    /* 称量值清水二 */
    @Column(name = "matl22")
    private String matL22;
    /* 称量值回收水 */
    @Column(name = "matl23")
    private String matL23;
    @Column(name = "stoname")
    private String stoName;
}
