spring:
  devtools:
    restart:
      exclude: /static/**,/templates/**
  datasource:
    url: jdbc:sqlserver://192.168.31.3:1433;databaseName=SPTERPNEWData
    username: sa
    password: TongXin2019
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  http:
    encoding:
      charset: utf-8
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 20MB
  main:
    allow-bean-definition-overriding: true
  redis:
    port: 6379
  cache:
    redis:
      time-to-live: 600000
    cache-names: cache1，cache2
  rabbitmq:
    host: localhost
    username: guest
    password: guest
mybatis:
  type-aliases-package: com.hntxrj.txerp.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: sqlserver
  reasonable: false
  support-methods-arguments: true
  params: countSql

app:
  timsdk:
    sdkAppID: 1400290495
    key: 79658d8c62dbd5cf02b5fc80d70ead6005801bcf57efa7b477c3a133aeec3738
  spterp:
    #  uploadpath: /Users/lhr/Desktop/blogUpload/articleImage/
    uploadpath: D:\spterp\header
    version: D:\Tomcat 8.0\webapps\ROOT\
    # erp 企业类型(用于判断是否走第三方接口的存储过程)
    erptype: 1
    # 合同附件上传路径
    contractAdjunctPath: /Users/haoranliu/MobleWebERP/SourceDirectory/spterp/log/
    # 任务单附件上传路径
    taskPlanAdjunctPath: /Users/haoranliu/MobleWebERP/SourceDirectory/spterp/log/
    taskSaleInvoiceUploadPath: /Users/haoranliu/IdeaProjects/spterp-phone/upload/
  checking:
    imgFilePath: D:\imgFilePath\
  cloud:
    CommunicationUrl: https://console.tim.qq.com/v4

    #    host: http://localhost:9501
    host: http://localhost:9501
    auth: ${app.cloud.host}/user/tokenUse
  jPush:
    url: https://api.jpush.cn/v3/push
    erpPhone:
      appKey: 26baeaf40bed37e5c274b843
      masterSecret: b9192be6883bec8d0e4e7b87
    erpDriver:
      appKey: 976c0ee7337b95b73a9b7342
      masterSecret: 7d7e853c1f6cdf25b1ec6724
    erpBuilder:
      appKey:
      masterSecret:

logging:
  file:
    #    name: spterp.%d{yyyy-MM-dd HH:mm:ss.SSS}.log
    path: /tmp/spterp/
    # 要保留日志的总大小
  level:
    com.hntxrj.mapper: DEBUG
server:
  port: 8088