spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tx-driver?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root

mybatis:
  type-aliases-package: com.hntxrj.driver.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true


app:
  host: https://api.hntxrj.com/
